version: '3'

# Define common configuration for all Spark worker services
x-spark-common: &spark-common
  image: bitnami/spark:latest  # Use the Bitnami Spark image
  volumes:  
    - ./jobs:/opt/bitnami/spark/jobs  # Maps the local 'jobs' directory to the container's jobs directory
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077  # Starts Spark worker and connects to the master
  depends_on:
    - spark-master  # Ensures the worker starts after the master
  environment:
    SPARK_MODE: Worker  # Specifies that this container will run as a Spark worker
    SPARK_WORKER_CORES: 2  # Sets the number of CPU cores for the worker
    SPARK_WORKER_MEMORY: 1g  # Sets the memory for the worker
    SPARK_MASTER_URL: spark://spark-master:7077  # URL for connecting to the Spark master
  networks:
    - datamasterylab  # Connects to a Docker network for communication with other containers

services:
  # Spark master service configuration
  spark-master:
    image: bitnami/spark:latest  # Use the Bitnami Spark image for the master
    container_name: spark-master  # Assign a name to the container
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs  # Maps the local 'jobs' directory to the container's jobs directory
    command: bin/spark-class org.apache.spark.deploy.master.Master  # Starts Spark in master mode
    ports:
      - "9898:8080"  # Maps port 8080 in the container (Spark UI) to port 9898 on your machine
      - "7877:7077"  # Maps port 7077 in the container (Spark communication) to port 7877 on your machine
    networks:
      - datamasterylab  # Connects to a Docker network for communication with other containers

  # Spark worker services using the common configuration
  spark-worker-1:
    <<: *spark-common  # Inherit common configuration for worker 1
  spark-worker-2:
    <<: *spark-common  # Inherit common configuration for worker 2
  spark-worker-3:
    <<: *spark-common  # Inherit common configuration for worker 3
  spark-worker-4:
    <<: *spark-common  # Inherit common configuration for worker 4

# Define the custom Docker network for the Spark cluster
networks:
  datamasterylab:
    driver: bridge  # Use the default bridge network driver for container communication
